# Generated by Django 5.2.13 on 2026-05-07 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        ('equipment', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_start_time', models.DateTimeField(verbose_name='Reception start date and time')),
                ('reception_end_time', models.DateTimeField(verbose_name='Reception end date and time')),
                ('reception_place', models.TextField(verbose_name='Reception location')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='accounts.administrator', verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['reception_start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='Reception result')),
                ('prescription', models.TextField(verbose_name='Prescription')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'Absent')], default='scheduled', max_length=10, verbose_name='Status')),
                ('clinic_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='equipment.clinicequipment', verbose_name='Clinic equipment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='accounts.doctor', verbose_name='Doctor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='documents.document', verbose_name='Document')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='patients.medicalcard', verbose_name='Medical record')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='scheduling.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Reception',
                'verbose_name_plural': 'Receptions',
                'ordering': ['-schedule__reception_start_time'],
            },
        ),
    ]
