# Generated by Django 5.2.13 on 2026-05-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Clinic Equipment Category',
                'verbose_name_plural': 'Clinic Equipment Categories',
            },
        ),
        migrations.CreateModel(
            name='ClinicEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Equipment name')),
                ('instruction', models.TextField(verbose_name='Instruction')),
                ('warranty_period', models.DateTimeField(verbose_name='Warranty period')),
                ('certificate', models.TextField(verbose_name='Certificate / License')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='equipment.clinicequipmentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Clinic Equipment',
                'verbose_name_plural': 'Clinic Equipments',
                'ordering': ['name'],
            },
        ),
    ]
