# Generated by Django 5.2.13 on 2026-05-08 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-20 digits, can include +, -, spaces).', regex='^\\+?[0-9\\s\\-\\(\\)]{10,20}$')], verbose_name='Phone number'),
        ),
    ]
