# Generated by Django 5.2.13 on 2026-05-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='last_login_date',
        ),
    ]
