# Generated by Django 5.2.13 on 2026-05-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Document content')),
                ('formation_date', models.DateField(verbose_name='Formation date')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.administrator', verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-formation_date'],
            },
        ),
    ]
