# Generated by Django 5.2.13 on 2026-05-08 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=10, verbose_name='Status')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_threads', to='accounts.administrator', verbose_name='Administrator')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='email_threads', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Email flow',
                'verbose_name_plural': 'Email flows',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('send_date', models.DateField(verbose_name='Send date')),
                ('send_time', models.TimeField(verbose_name='Send time')),
                ('sender_type', models.CharField(choices=[('admin', 'Administrator'), ('patient', 'Patient')], max_length=20, verbose_name='Sender type')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.email', verbose_name='Email flow')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['send_date', 'send_time'],
            },
        ),
    ]
