# Generated by Django 5.2.13 on 2026-05-08 09:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_administrator_last_login_date'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('administrator', 'patient')},
        ),
    ]
