# Generated by Django 5.2.13 on 2026-05-07 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_info', models.TextField(verbose_name='Allergy information')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Blood group')),
                ('current_medication', models.TextField(verbose_name='Medications currently being used')),
                ('date_of_update', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Medical record',
                'verbose_name_plural': 'Medical records',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_content', models.TextField(verbose_name='Diagnostic content')),
                ('diagnosis_date', models.DateField(verbose_name='Date of diagnosis')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.medicalcard', verbose_name='Medical record')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_analysis_samples', models.TextField(verbose_name='List of analysis samples')),
                ('analysis_result', models.TextField(verbose_name='Analysis result')),
                ('analysis_date', models.DateField(verbose_name='Analysis date')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.medicalcard', verbose_name='Medical record')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50, verbose_name='Name of the disease')),
                ('treatment_date', models.DateField(verbose_name='Treatment date')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='patients.medicalcard', verbose_name='Medical record')),
            ],
            options={
                'verbose_name': 'Medical history',
                'verbose_name_plural': 'Medical histories',
                'ordering': ['-treatment_date'],
            },
        ),
    ]
